# Generated by Django 5.0.6 on 2024-05-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodelivery', '0002_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiochunk',
            name='file_path',
            field=models.FilePathField(blank=True, help_text='Path where the file is stored', max_length=255, null=True, verbose_name='File path'),
        ),
    ]
