# Generated by Django 5.0.6 on 2024-05-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiodelivery', '0003_alter_audiochunk_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiochunk',
            name='file_path',
        ),
    ]
