# Generated by Django 5.0.6 on 2024-05-21 12:55

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodelivery', '0005_audiochunk_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiochunk',
            name='file_path',
            field=models.FilePathField(blank=True, help_text='Path where the file is stored', max_length=255, null=True, path=pathlib.PureWindowsPath('D:/workspace/WebDropStudio/audiodelivery/streamer/chunks'), verbose_name='File path'),
        ),
    ]
