# Generated by Django 5.0.6 on 2024-05-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiodelivery', '0006_alter_audiochunk_file_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'permissions': (('can_retrieve', 'Can User retrieve Audio infos'), ('can_upload', 'Can User upload new Audio')), 'verbose_name': 'Audio', 'verbose_name_plural': 'Audios'},
        ),
    ]
